### PR TITLE
Updated the README and initialized the react app.

### PR DESCRIPTION
**Pull request by daniel-hermansen**

### CODE REVIEW

**Comment by charlesc-ifit** [comment]
(sorry, haven't forgotten this, just a bit busier than normal. hoping to get to this before fri!)

**Comment by charlesc-ifit** [comment]
@daniel-hermansen - (from my notes from our sync last Fri) I was looking at the eslint config from Create React App - looks like it's a pretty basic. It'd be a good idea to start with the [AirBnb style guide](https://github.com/airbnb/javascript) b/c it's one of the most popular around at the moment. (And after you get a feel for these rules/linting in general, we can customize to your tastes.)

The set up instructions are in the [npm package page](https://www.npmjs.com/package/eslint-config-airbnb) - if you like we can:
1. set it up in this PR
2. set it up in a follow up PR
3. walk through and do it together


For completeness, here are a couple other tools often used with or in place of the AirBnb style guide
- https://standardjs.com/ - a completely different style guide
- https://prettier.io/ - a popular code formatting tool that supplements (but doesn't replace) the linting tool. See [this explanation](https://prettier.io/docs/en/comparison.html)

**Review by charlesc-ifit — COMMENTED** [review]
sorry for the delay on this! just took a look, and looks pretty good to me! couple quick questions before I approve:
- did you wanna do any extra linting set up (my comment about the different style guides) in this PR? Or maybe a follow up PR?  
- I saw that this React client code lived in a `fitness-app` folder nested within this repo's root folder, though all of these React files could just live in the root folder. Was this an intentional choice? Just wanna get a lil extra context

Screen Shot 2021-09-09 at 9 59 02 PM


feel free to reply on this PR or we can talk about it at our next sync, whatever's easiest for ya!

**Comment by daniel-hermansen** [comment]
Hey Charles, I'm sorry that I haven't responded yet on this thread. I would like to go over implementing the linting rules from the AirBNB styling guide with you this week when we meet if that is okay. I will close this PR and we can get it implemented on the next PR.

**Pull request merged**
